# インポート

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

# データの読み込み

In [2]:
traffic_accident_data = pd.read_csv("https://www.npa.go.jp/publications/statistics/koutsuu/opendata/2020/honhyo_2020.csv",
                                                        encoding="shift-jis")
traffic_accident_data_19 = pd.read_csv("https://www.npa.go.jp/publications/statistics/koutsuu/opendata/2019/honhyo_2019.csv",
                                                        encoding="shift-jis")

traffic_accident_data = traffic_accident_data.append(traffic_accident_data_19).reset_index(drop=True)

In [3]:
traffic_accident_data.head()

,資料区分,都道府県コード,警察署等コード,本票番号,事故内容,死者数,負傷者数,路線コード,上下線,地点コード,市区町村コード,発生日時 年,発生日時 月,発生日時 日,発生日時 時,発生日時 分,昼夜,天候,地形,路面状態,道路形状,環状交差点の直径,信号機,一時停止規制 標識（当事者A）,一時停止規制 表示（当事者A）,一時停止規制 標識（当事者B）,一時停止規制 表示（当事者B）,車道幅員,道路線形,衝突地点,ゾーン規制,中央分離帯施設等,歩車道区分,事故類型,年齢（当事者A）,年齢（当事者B）,当事者種別（当事者A）,当事者種別（当事者B）,用途別（当事者A）,用途別（当事者B）,車両形状（当事者A）,車両形状（当事者B）,速度規制（指定のみ）（当事者A）,速度規制（指定のみ）（当事者B）,車両の衝突部位（当事者A）,車両の衝突部位（当事者B）,車両の損壊程度（当事者A）,車両の損壊程度（当事者B）,エアバッグの装備（当事者A）,エアバッグの装備（当事者B）,サイドエアバッグの装備（当事者A）,サイドエアバッグの装備（当事者B）,人身損傷程度（当事者A）,人身損傷程度（当事者B）,地点 緯度（北緯）,地点 経度（東経）,曜日(発生年月日),祝日(発生年月日)
0,1,10,59,1,2,0,1,40010,1,0,234,2020,1,6,7,20,11,2,3,3,14,0,7,0,23,0,23,4,9,20,70,1,4,21,45,65,3,4,31,31,1,1,4,4,42,13,3,3,2,1,2,2,2,4,425637403,1413108483,2,3
1,1,10,59,2,2,0,1,40010,1,0,213,2020,1,16,6,39,23,1,3,1,14,0,7,0,23,0,23,4,9,1,70,1,4,21,65,45,3,13,31,1,1,11,10,10,80,16,2,2,2,2,2,2,4,2,424247129,1413908484,5,3
2,1,10,59,3,2,0,2,40130,1,0,224,2020,1,5,6,15,23,5,3,3,14,0,7,0,23,0,23,4,9,1,70,6,3,21,1,35,3,3,31,31,1,1,4,4,40,10,1,2,1,2,2,2,2,2,425256568,1413936088,1,3
3,1,10,59,4,2,0,1,40130,1,0,209,2020,1,24,15,20,12,5,3,3,11,0,7,0,23,0,23,4,9,1,70,6,3,21,55,55,3,3,31,31,1,1,4,4,47,84,2,2,1,2,1,2,4,2,425609108,1420528287,6,3
4,1,10,101,1,2,0,1,39990,0,0,101,2019,12,22,18,51,22,2,1,1,1,0,7,1,22,9,22,15,9,30,70,4,2,21,35,25,3,3,31,31,1,1,3,3,10,40,3,3,2,2,2,2,4,2,430257558,1412117886,1,3

In [5]:
traffic_accident_data.describe()

,資料区分,都道府県コード,警察署等コード,本票番号,事故内容,死者数,負傷者数,路線コード,上下線,地点コード,市区町村コード,発生日時 年,発生日時 月,発生日時 日,発生日時 時,発生日時 分,昼夜,天候,地形,路面状態,道路形状,環状交差点の直径,信号機,一時停止規制 標識（当事者A）,一時停止規制 表示（当事者A）,一時停止規制 標識（当事者B）,一時停止規制 表示（当事者B）,車道幅員,道路線形,衝突地点,ゾーン規制,中央分離帯施設等,歩車道区分,事故類型,年齢（当事者A）,年齢（当事者B）,当事者種別（当事者A）,当事者種別（当事者B）,用途別（当事者A）,用途別（当事者B）,車両形状（当事者A）,車両形状（当事者B）,速度規制（指定のみ）（当事者A）,速度規制（指定のみ）（当事者B）,車両の衝突部位（当事者A）,車両の衝突部位（当事者B）,車両の損壊程度（当事者A）,車両の損壊程度（当事者B）,エアバッグの装備（当事者A）,エアバッグの装備（当事者B）,サイドエアバッグの装備（当事者A）,サイドエアバッグの装備（当事者B）,人身損傷程度（当事者A）,人身損傷程度（当事者B）,地点 緯度（北緯）,地点 経度（東経）,曜日(発生年月日),祝日(発生年月日)
count,690415.0,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,690415.000000,6.904150e+05,6.904150e+05,690415.000000,690415.000000
mean,1.0,55.121725,183.653821,335.807892,1.991430,0.008769,1.203987,25561.910739,0.217027,181.636478,194.231526,2019.418999,6.626853,15.905116,12.995526,28.088855,14.634581,1.488218,1.711001,1.177534,6.868899,0.000048,5.514049,3.002271,22.509718,2.825724,22.611357,7.974899,8.267052,14.534896,69.256247,3.599489,2.421367,19.221128,41.461068,35.954807,7.419837,26.453100,27.451549,19.315381,2.387386,1.658799,5.339771,3.504062,31.575351,23.443648,2.901002,2.343716,1.824290,0.998413,1.859602,1.034982,3.580600,2.237519,3.504190e+08,1.364658e+09,4.121512,2.887166
std,0.0,21.125832,158.937797,403.725915,0.092178,0.095547,0.596516,22067.544716,0.557067,731.676939,75.294243,0.523614,3.532835,8.770813,4.841313,17.253123,4.313546,0.766084,0.781834,0.448340,6.037829,0.009399,2.572414,4.141120,0.625169,4.129554,0.556089,6.024626,2.163433,13.963603,7.125015,1.583371,0.863995,7.567163,20.700286,23.572093,10.678027,24.083072,9.745327,15.002426,3.558211,3.378604,3.315212,3.613200,25.014008,20.269246,0.503139,1.130277,0.523699,0.977216,0.500110,0.995138,0.818618,0.906817,2.108365e+07,3.859793e+07,1.912512,0.425477
min,1.0,10.000000,50.000000,1.000000,1.000000,0.000000,0.000000,10.000000,0.000000,0.000000,101.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,11.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,21.000000,0.000000,21.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000,1.000000
25%,1.0,43.000000,107.000000,89.000000,2.000000,0.000000,1.000000,10130.000000,0.000000,0.000000,131.000000,2019.000000,3.000000,8.000000,9.000000,14.000000,12.000000,1.000000,1.000000,1.000000,1.000000,0.000000,4.000000,0.000000,22.000000,0.000000,22.000000,3.000000,9.000000,1.000000,70.000000,4.000000,2.000000,21.000000,25.000000,25.000000,3.000000,4.000000,31.000000,0.000000,1.000000,0.000000,3.000000,0.000000,10.000000,10.000000,3.000000,2.000000,2.000000,0.000000,2.000000,0.000000,4.000000,2.000000,3.436333e+08,1.345956e+09,2.000000,3.000000
50%,1.0,53.000000,120.000000,216.000000,2.000000,0.000000,1.000000,30000.000000,0.000000,0.000000,203.000000,2019.000000,7.000000,16.000000,13.000000,30.000000,12.000000,1.000000,2.000000,1.000000,7.000000,0.000000,7.000000,0.000000,23.000000,0.000000,23.000000,5.000000,9.000000,1.000000,70.000000,4.000000,2.000000,21.000000,45.000000,35.000000,3.000000,14.000000,31.000000,31.000000,1.000000,1.000000,4.000000,3.000000,20.000000,20.000000,3.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,2.000000,3.508173e+08,1.370953e+09,4.000000,3.000000
75%,1.0,63.000000,204.000000,433.000000,2.000000,0.000000,1.000000,37000.000000,0.000000,0.000000,213.000000,2020.000000,10.000000,24.000000,17.000000,43.000000,21.000000,2.000000,2.000000,1.000000,14.000000,0.000000,7.000000,9.000000,23.000000,9.000000,23.000000,14.000000,9.000000,30.000000,70.000000,5.000000,3.000000,21.000000,55.000000,55.000000,4.000000,51.000000,31.000000,31.000000,1.000000,1.000000,10.000000,4.000000,50.000000,30.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,4.000000,2.000000,3.546532e+08,1.393620e+09,6.000000,3.000000
max,1.0,97.000000,900.000000,9011.000000,2.000000,4.000000,31.000000,99009.000000,2.000000,9999.000000,996.000000,2020.000000,12.000000,31.000000,23.000000,59.000000,23.000000,5.000000,3.000000,5.000000,37.000000,3.000000,8.000000,9.000000,23.000000,9.000000,23.000000,19.000000,9.000000,30.000000,70.000000,6.000000,4.000000,61.000000,75.000000,75.000000,76.000000,76.000000,31.000000,31.000000,11.000000,11.000000,10.000000,10.000000,88.000000,88.000000,4.000000,4.000000,2.000000,2.000000,2.000000,2.000000,4.000000,4.000000,4.527074e+08,1.453544e+09,7.000000,3.000000

# Pandas-Profiling

In [6]:
# import pandas_profiling as pdp
# pdp.ProfileReport(traffic_accident_data)

# 前処理

## accident_date

In [9]:
traffic_accident_data[['発生日時　　年', '発生日時　　月', '発生日時　　日', '発生日時　　時', '発生日時　　分']].head()

   発生日時　　年  発生日時　　月  発生日時　　日  発生日時　　時  発生日時　　分
0     2020        1        6        7       20
1     2020        1       16        6       39
2     2020        1        5        6       15
3     2020        1       24       15       20
4     2019       12       22       18       51

In [10]:
traffic_accident_data["accident_date"] = \
pd.to_datetime(traffic_accident_data[['発生日時　　年', '発生日時　　月', '発生日時　　日', '発生日時　　時', '発生日時　　分']].\
               apply(lambda x: '{}-{}-{} {}:{}'.format(x[0], x[1], x[2], x[3], x[4]), axis=1))

In [11]:
traffic_accident_data["accident_date"].head()

0   2020-01-06 07:20:00
1   2020-01-16 06:39:00
2   2020-01-05 06:15:00
3   2020-01-24 15:20:00
4   2019-12-22 18:51:00
Name: accident_date, dtype: datetime64[ns]

## 警察

In [12]:
# police_code_df = pd.read_csv("police_code.csv")
# police_code_df = police_code_df.rename(columns={'police_cd':'警察署等コード'})
# police_code_df = police_code_df[~police_code_df["警察署等コード"].duplicated(keep="first")].reset_index(drop=True)
# police_code_df.tail()

In [13]:
# traffic_accident_data = pd.merge(traffic_accident_data,
#                                                     police_code_df.drop(columns=["pref_cd", "pref_name"]),
#                                                      on="警察署等コード", how="left")

## 都道府県

In [15]:
pref_code_df = pd.read_csv("data/pref_code_conv.csv")
pref_code_df = pref_code_df.rename(columns={'pref_cd':'都道府県コード'})
pref_code_df.tail()

    都道府県コード pref_name  genuine_pref_cd genuine_pref_name
46       93        熊本               43                熊本
47       94        大分               44                大分
48       95        宮崎               45                宮崎
49       96       鹿児島               46               鹿児島
50       97        沖縄               47                沖縄

In [16]:
traffic_accident_data[['都道府県コード']].head()

   都道府県コード
0       10
1       10
2       10
3       10
4       10

In [17]:
traffic_accident_data = pd.merge(traffic_accident_data, pref_code_df,
                                                     on="都道府県コード", how="left")

## 地域コード

In [18]:
traffic_accident_data[['genuine_pref_cd', '市区町村コード']].head()

   genuine_pref_cd  市区町村コード
0                1      234
1                1      213
2                1      224
3                1      209
4                1      101

In [19]:
traffic_accident_data["tiiki-code"] = traffic_accident_data[['genuine_pref_cd', '市区町村コード']]\
                                                            .apply(lambda x: '{}{}'.format(x[0], x[1]), axis=1)

In [20]:
traffic_accident_data["tiiki-code"].head()

0    1234
1    1213
2    1224
3    1209
4    1101
Name: tiiki-code, dtype: object

In [21]:
traffic_accident_data["tiiki-code"].value_counts()

28201    6127
45201    5369
11202    4953
11201    4630
37201    4535
         ...
8363        1
32526       1
1425        1
1667        1
29385       1
Name: tiiki-code, Length: 1868, dtype: int64

In [22]:
#https://www.soumu.go.jp/toukei_toukatsu/index/seido/9-5.htm

### 地域コードから地域をmerge

In [25]:
city_code_df = pd.read_csv("https://www.soumu.go.jp/main_content/000608358.csv", encoding="shift-jis")
city_code_df = city_code_df.rename(columns={"sityouson-code":'市区町村コード'})
city_code_df["tiiki-code"] = city_code_df["tiiki-code"].astype(str)
city_code_df.head()

,ken-code,市区町村コード,tiiki-code,ken-name,sityouson-name1,sityouson-name2,sityouson-name3,yomigana
0,1,0,1000,北海道,NaN,NaN,NaN,ほっかいどう
1,1,100,1100,北海道,札幌市,NaN,NaN,さっぽろし
2,1,101,1101,北海道,札幌市,NaN,中央区,ちゅうおうく
3,1,102,1102,北海道,札幌市,NaN,北区,きたく
4,1,103,1103,北海道,札幌市,NaN,東区,ひがしく

In [26]:
%%time
traffic_accident_data = pd.merge(traffic_accident_data,
                                                     city_code_df.drop(columns=["ken-code", "市区町村コード", "yomigana"]),
                                                     on="tiiki-code", how="left")

CPU times: user 203 ms, sys: 132 ms, total: 335 ms
Wall time: 348 ms

In [27]:
traffic_accident_data.head()

,資料区分,都道府県コード,警察署等コード,本票番号,事故内容,死者数,負傷者数,路線コード,上下線,地点コード,市区町村コード,発生日時 年,発生日時 月,発生日時 日,発生日時 時,発生日時 分,昼夜,天候,地形,路面状態,道路形状,環状交差点の直径,信号機,一時停止規制 標識（当事者A）,一時停止規制 表示（当事者A）,一時停止規制 標識（当事者B）,一時停止規制 表示（当事者B）,車道幅員,道路線形,衝突地点,ゾーン規制,中央分離帯施設等,歩車道区分,事故類型,年齢（当事者A）,年齢（当事者B）,当事者種別（当事者A）,当事者種別（当事者B）,用途別（当事者A）,用途別（当事者B）,車両形状（当事者A）,車両形状（当事者B）,速度規制（指定のみ）（当事者A）,速度規制（指定のみ）（当事者B）,車両の衝突部位（当事者A）,車両の衝突部位（当事者B）,車両の損壊程度（当事者A）,車両の損壊程度（当事者B）,エアバッグの装備（当事者A）,エアバッグの装備（当事者B）,サイドエアバッグの装備（当事者A）,サイドエアバッグの装備（当事者B）,人身損傷程度（当事者A）,人身損傷程度（当事者B）,地点 緯度（北緯）,地点 経度（東経）,曜日(発生年月日),祝日(発生年月日),accident_date,pref_name,genuine_pref_cd,genuine_pref_name,tiiki-code,ken-name,sityouson-name1,sityouson-name2,sityouson-name3
0,1,10,59,1,2,0,1,40010,1,0,234,2020,1,6,7,20,11,2,3,3,14,0,7,0,23,0,23,4,9,20,70,1,4,21,45,65,3,4,31,31,1,1,4,4,42,13,3,3,2,1,2,2,2,4,425637403,1413108483,2,3,2020-01-06 07:20:00,北海道（札幌方面）,1,北海道,1234,北海道,NaN,NaN,北広島市
1,1,10,59,2,2,0,1,40010,1,0,213,2020,1,16,6,39,23,1,3,1,14,0,7,0,23,0,23,4,9,1,70,1,4,21,65,45,3,13,31,1,1,11,10,10,80,16,2,2,2,2,2,2,4,2,424247129,1413908484,5,3,2020-01-16 06:39:00,北海道（札幌方面）,1,北海道,1213,北海道,NaN,NaN,苫小牧市
2,1,10,59,3,2,0,2,40130,1,0,224,2020,1,5,6,15,23,5,3,3,14,0,7,0,23,0,23,4,9,1,70,6,3,21,1,35,3,3,31,31,1,1,4,4,40,10,1,2,1,2,2,2,2,2,425256568,1413936088,1,3,2020-01-05 06:15:00,北海道（札幌方面）,1,北海道,1224,北海道,NaN,NaN,千歳市
3,1,10,59,4,2,0,1,40130,1,0,209,2020,1,24,15,20,12,5,3,3,11,0,7,0,23,0,23,4,9,1,70,6,3,21,55,55,3,3,31,31,1,1,4,4,47,84,2,2,1,2,1,2,4,2,425609108,1420528287,6,3,2020-01-24 15:20:00,北海道（札幌方面）,1,北海道,1209,北海道,NaN,NaN,夕張市
4,1,10,101,1,2,0,1,39990,0,0,101,2019,12,22,18,51,22,2,1,1,1,0,7,1,22,9,22,15,9,30,70,4,2,21,35,25,3,3,31,31,1,1,3,3,10,40,3,3,2,2,2,2,4,2,430257558,1412117886,1,3,2019-12-22 18:51:00,北海道（札幌方面）,1,北海道,1101,北海道,札幌市,NaN,中央区

## 高速道路

In [28]:
road_code_df = pd.read_csv("data/road_code.csv")

## 事故内容

In [35]:
traffic_accident_data["事故内容"].value_counts(dropna=False)

2    684498
1      5917
Name: 事故内容, dtype: int64

In [39]:
traffic_accident_data["事故内容"].value_counts(normalize=True)

2    0.99143
1    0.00857
Name: 事故内容, dtype: float64

In [38]:
traffic_accident_data["accident_type"] = \
np.where(traffic_accident_data["事故内容"] == 1, "死亡", np.where(traffic_accident_data["事故内容"] == 2, "負傷", None))

numpy.where()は、条件式conditionを満たす場合（真Trueの場合）はx、満たさない場合（偽Falseの場合）はyとするndarrayを返す関数。

```
if traffic_accident_data["事故内容"] == 1:
    死亡
elif traffic_accident_data["事故内容"] == 2:
    負傷
else:
    None

```

In [36]:
traffic_accident_data["accident_type"].value_counts(dropna=False)

負傷    684498
死亡      5917
Name: accident_type, dtype: int64

## 路面コード

In [41]:
traffic_accident_data["路線コード"].head()

0    40010
1    40010
2    40130
3    40130
4    39990
Name: 路線コード, dtype: int64

In [42]:
map(lambda text:text[0:4], traffic_accident_data["路線コード"].astype(str))

第一引数に関数、第二引数に加工元となる値群を指定

map関数の第一引数は関数の形で指定する必要はなく、lambda式でも良いとされています。lambda（ラムダ）とはある処理に名前を付けずに定義したもののことで、def文によって関数定義をすることもありません。

In [43]:
list(map(lambda text:text[0:4], traffic_accident_data["路線コード"].astype(str)))

['4001',
 '4001',
 '4013',
 '4013',
 '3999',
 '9900',
 '3999',
 '2235',
 '2300',
 '3999',
 '360',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '360',
 '3999',
 '50',
 '2300',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '360',
 '360',
 '3999',
 '3999',
 '50',
 '3999',
 '360',
 '3999',
 '3999',
 '3999',
 '1160',
 '120',
 '2235',
 '3999',
 '3999',
 '120',
 '50',
 '3999',
 '3999',
 '1003',
 '3999',
 '2740',
 '3999',
 '3999',
 '3999',
 '3999',
 '9900',
 '3999',
 '3999',
 '120',
 '120',
 '3999',
 '3999',
 '3999',
 '3999',
 '1003',
 '3999',
 '2740',
 '1508',
 '2740',
 '1003',
 '3999',
 '1003',
 '9900',
 '3999',
 '3999',
 '2550',
 '3999',
 '2364',
 '3999',
 '2364',
 '1090',
 '3999',
 '120',
 '1003',
 '3999',
 '3517',
 '3517',
 '3999',
 '120',
 '3999',
 '3999',
 '1090',
 '3999',
 '3527',
 '3999',
 '2236',
 '3527',
 '3999',
 '1161',
 '3999',
 '3999',
 '50',
 '50',
 '3999',
 '2089',
 '1160',
 '2236',
 '1161',
 '1082',
 '1507',
 '3999',
 '2235',
 '3999',
 '3999',
 '9900',
 '3999',
 '3999',
 '1090',
 '3999',
 '2236',
 '3999',
 '1160',
 '3999',
 '1090',
 '3999',
 '9900',
 '3506',
 '2219',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '50',
 '3999',
 '50',
 '3999',
 '2219',
 '3999',
 '3999',
 '2219',
 '3999',
 '9900',
 '9900',
 '3999',
 '1090',
 '2740',
 '3999',
 '3999',
 '3999',
 '2750',
 '3999',
 '3999',
 '3999',
 '50',
 '3999',
 '2084',
 '3999',
 '3999',
 '3999',
 '2740',
 '3999',
 '50',
 '2740',
 '2740',
 '3999',
 '3999',
 '3999',
 '2219',
 '2740',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '9900',
 '3506',
 '3999',
 '2084',
 '120',
 '3999',
 '120',
 '3999',
 '3999',
 '1137',
 '1046',
 '120',
 '1137',
 '120',
 '2750',
 '120',
 '1137',
 '2550',
 '2661',
 '360',
 '1019',
 '1019',
 '360',
 '360',
 '360',
 '3999',
 '2999',
 '3999',
 '3999',
 '3999',
 '2068',
 '2344',
 '2344',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '1045',
 '1006',
 '1006',
 '3999',
 '2487',
 '3999',
 '3608',
 '2580',
 '2340',
 '3999',
 '3609',
 '1006',
 '1003',
 '1003',
 '3888',
 '120',
 '3999',
 '2750',
 '2750',
 '2750',
 '121',
 '3999',
 '4510',
 '3999',
 '3999',
 '380',
 '380',
 '3999',
 '3999',
 '50',
 '9900',
 '50',
 '50',
 '50',
 '3999',
 '3999',
 '3999',
 '3999',
 '1020',
 '1020',
 '3999',
 '50',
 '50',
 '3930',
 '3888',
 '3930',
 '2300',
 '2158',
 '2760',
 '3888',
 '2760',
 '370',
 '370',
 '2999',
 '360',
 '3999',
 '3999',
 '3999',
 '2419',
 '1109',
 '3999',
 '3999',
 '360',
 '2999',
 '2480',
 '2480',
 '3999',
 '2726',
 '3999',
 '3999',
 '2480',
 '2419',
 '360',
 '360',
 '3613',
 '3999',
 '3999',
 '2350',
 '360',
 '3999',
 '3999',
 '3999',
 '2479',
 '360',
 '360',
 '3888',
 '360',
 '3999',
 '3999',
 '2340',
 '3999',
 '3999',
 '3999',
 '2760',
 '3999',
 '2340',
 '3999',
 '3999',
 '3888',
 '3999',
 '360',
 '3999',
 '3999',
 '360',
 '2350',
 '9900',
 '3999',
 '3999',
 '2340',
 '9900',
 '2350',
 '3888',
 '3888',
 '3999',
 '3999',
 '3999',
 '3999',
 '2300',
 '2300',
 '3999',
 '1082',
 '3999',
 '3999',
 '2300',
 '3999',
 '3999',
 '3999',
 '3999',
 '2300',
 '4530',
 '4530',
 '1090',
 '3999',
 '3999',
 '9900',
 '3999',
 '3999',
 '3501',
 '3999',
 '3999',
 '1082',
 '9900',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '2090',
 '1112',
 '3999',
 '2999',
 '2032',
 '3999',
 '3999',
 '3515',
 '3999',
 '3999',
 '3515',
 '2090',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3370',
 '1141',
 '3999',
 '3370',
 '3999',
 '3999',
 '2551',
 '3999',
 '3370',
 '3999',
 '2084',
 '3999',
 '2310',
 '3999',
 '3999',
 '3999',
 '3999',
 '1112',
 '3999',
 '2310',
 '3999',
 '1141',
 '2310',
 '3999',
 '3515',
 '3370',
 '3999',
 '2999',
 '2090',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '1141',
 '3999',
 '3999',
 '1044',
 '3999',
 '3999',
 '3999',
 '1519',
 '1519',
 '3999',
 '1090',
 '9900',
 '2156',
 '3999',
 '3999',
 '9900',
 '2156',
 '9900',
 '3999',
 '3521',
 '360',
 '9900',
 '1519',
 '360',
 '9900',
 '3999',
 '3999',
 '360',
 '3999',
 '1090',
 '1519',
 '2236',
 '3522',
 '2236',
 '3999',
 '9900',
 '1519',
 '1519',
 '3520',
 '1519',
 '2999',
 '3522',
 '4530',
 '360',
 '3999',
 '3522',
 '1090',
 '3999',
 '3999',
 '3999',
 '360',
 '360',
 '3510',
 '9900',
 '3999',
 '4530',
 '3999',
 '360',
 '360',
 '1082',
 '3999',
 '3999',
 '1082',
 '3522',
 '3999',
 '2236',
 '3999',
 '3521',
 '360',
 '3999',
 '2085',
 '2740',
 '2085',
 '2085',
 '3999',
 '3999',
 '3999',
 '3999',
 '120',
 '3999',
 '3999',
 '3999',
 '3999',
 '3527',
 '3999',
 '2235',
 '3999',
 '50',
 '3999',
 '1044',
 '3999',
 '50',
 '50',
 '50',
 '3999',
 '9900',
 '2235',
 '1100',
 '50',
 '3999',
 '3999',
 '50',
 '1100',
 '9900',
 '2161',
 '50',
 '9900',
 '3999',
 '3999',
 '3999',
 '50',
 '3999',
 '1096',
 '3999',
 '1100',
 '50',
 '50',
 '1100',
 '2270',
 '2280',
 '9900',
 '50',
 '2999',
 '50',
 '3999',
 '3999',
 '3999',
 '2270',
 '3999',
 '3999',
 '3999',
 '3999',
 '50',
 '3999',
 '3888',
 '2999',
 '2675',
 '1123',
 '9900',
 '2270',
 '4004',
 '4004',
 '5004',
 '4014',
 '4004',
 '120',
 '3999',
 '2370',
 '3999',
 '400',
 '3999',
 '122',
 '1091',
 '2025',
 '3999',
 '2999',
 '1023',
 '3999',
 '120',
 '3999',
 '122',
 '120',
 '3999',
 '1091',
 '3999',
 '3999',
 '3999',
 '3999',
 '120',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '400',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '3999',
 '9900',
 '3888',
 '1047',
 '2320',
 '3999',
 '3888',
 '5519',
 '9900',
 '3999',
 '390',
 '1091',
 '3999',
 '3999',
 '2999',
 '1091',
 '1150',
 '1150',
 '2107',
 '3999',
 '1091',
 '3999',
 '3888',
 '3999',
 '1091',
 '2999',
 '3999',
 '9900',
 '1039',
 '3999',
 '390',
 '3999',
 '3999',
 '2370',
 '3999',
 '1091',
 '2999',
 '2999',
 '2370',
 '3999',
 '4014',
 '4014',
 '1127',
 '380',
 '3999',
 '3999',
 '3999',
 '9900',
 '3999',
 '1127',
 '3999',
 '1056',
 '3999',
 '3999',
 '9900',
 '9900',
 '3888',
 '1127',
 '380',
 '3999',
 '440',
 '3999',
 '9900',
 '380',
 '2400',
 '1126',
 '440',
 '2720',
 '2720',
 '3888',
 '2269',
 '1146',
 '2433',
 '1125',
 '2360',
 '3999',
 '380',
 '1125',
 '3999',
 '3999',
 '3999',
 '1125',
 '9900',
 '3999',
 '3999',
 '3999',
 '2433',
 '3999',
 '2410',
 '3999',
 '3999',
 '3888',
 '3888',
 '2999',
 '2022',
 '2604',
 '3902',
 '3902',
 '2604',
 '390',
 '3888',
 '3999',
 '3999',
 '390',
 '3999',
 '1030',
 '3888',
 '1030',
 '5006',
 '40',
 '9900',
 '73',
 '9900',
 '70',
 '2011',
 '73',
 '73',
 '3000',
 '1014',
 '8500',
 '9900',
 '70',
 '3000',
 '3000',
 '1021',
 '3000',
 '1021',
 '73',
 '3000',
 '1030',
 '73',
 '3000',
 '2801',
 '3000',
 '3000',
 '70',
 '3000',
 '3000',
 '2018',
 '3000',
 '1030',
 '1030',
 '3000',
 '2221',
 '1030',
 '2018',
 '70',
 '3000',
 '1030',
 '9900',
 '73',
 '70',
 '3000',
 '1033',
 '3000',
 '3000',
 '1002',
 '1002',
 '3000',
 '3000',
 '1015',
 '3000',
 '3000',
 '70',
 '1020',
 '3000',
 '2001',
 '1044',
 '70',
 '3000',
 '3000',
 '3000',
 '3000',
 '1015',
 '3000',
 '3000',
 '70',
 '3000',
 '3000',
 '9900',
 '1002',
 '2090',
 '9900',
 '70',
 '450',
 '3000',
 '3000',
 '1043',
 '450',
 '3000',
 '1040',
 '3000',
 '3000',
 '9900',
 '3000',
 '3000',
 '3000',
 '9900',
 '3000',
 '450',
 '450',
 '3000',
 '1004',
 '3000',
 '3000',
 '3000',
 '2019',
 '9900',
 '3000',
 '3000',
 '4540',
 '3000',
 '9900',
 '3000',
 '1047',
 '3000',
 '4540',
 '450',
 '3000',
 '3000',
 '3000',
 '3000',
 '3000',
 '3000',
 '3000',
 '3000',
 '9900',
 '450',
 '450',
 '1040',
 '1047',
 '4540',
 '450',
 '3000',
 '3000',
 '2192',
 '2001',
 '1020',
 '3000',
 '2192',
 '3000',
 '70',
 '3000',
 '3000',
 '9900',
 '1010',
 '3000',
 '2104',
 '2108',
 '3390',
 '7000',
 '3390',
 '9900',
 '2064',
 '2064',
 '3000',
 '3000',
 '2791',
 '1035',
 '3380',
 '2790',
 '3380',
 '2098',
 '3000',
 '3000',
 '3000',
 '450',
 '1005',
 '3000',
 '3000',
 '2020',
 '3380',
 '9900',
 '3000',
 '450',
 '3000',
 '9900',
 '1050',
 '3000',
 '3000',
 '3000',
 '3000',
 '40',
 '40',
 '3000',
 '3000',
 '3000',
 '1020',
 '2106',
 '9900',
 '2106',
 '1010',
 '2106',
 '1006',
 '2790',
 '2060',
 '40',
 '40',
 '40',
 '40',
 '3940',
 '40',
 '2016',
 '3940',
 '2193',
 '1014',
 '3000',
 '2193',
 '3000',
 '3000',
 '3000',
 '70',
 '1032',
 '1014',
 '3000',
 '1031',
 '1031',
 '40',
 '4540',
 '1030',
 '3000',
 '1033',
 '1033',
 '3000',
 '3391',
 '3000',
 '4101',
 '4102',
 '2900',
 '3000',
 '3000',
 '3000',
 '3000',
 '40',
 '3960',
 '3000',
 '3000',
 '4550',
 '1013',
 '3000',
 '40',
 '40',
 '461',
 '3000',
 '3000',
 '460',
 '3000',
 '40',
 '3000',
 '4550',
 '1002',
 '3960',
 '3000',
 '1016',
 '3000',
 '40',
 '2820',
 '2810',
 '3000',
 '3000',
 '1046',
 '9500',
 '3000',
 '40',
 '40',
 '1025',
 '2207',
 '3000',
 '2830',
 '3000',
 '40',
 '3000',
 '2286',
 '3000',
 '3000',
 '3000',
 '3000',
 '2507',
 '3000',
 '3000',
 '3000',
 '2507',
 '3000',
 '1070',
 '3000',
 '3000',
 '3000',
 '1013',
 '3000',
 '40',
 '3000',
 '3000',
 '1013',
 '1070',
 '1014',
 '3970',
 '9900',
 '3000',
 '2236',
 '40',
 '3970',
 '40',
 '3000',
 ...]

In [44]:
traffic_accident_data["road_cd_f4"] = list(map(lambda text:text[0:4], traffic_accident_data["路線コード"].astype(str)))
traffic_accident_data["road_cd_f4"] = traffic_accident_data.road_cd_f4.astype(int)

traffic_accident_data["road_cd_l1"] = list(map(lambda text:text[-1], traffic_accident_data["路線コード"].astype(str)))
traffic_accident_data["road_cd_l1"] = traffic_accident_data.road_cd_l1.astype(int)

In [45]:
traffic_accident_data.road_cd_f4.head()

0    4001
1    4001
2    4013
3    4013
4    3999
Name: road_cd_f4, dtype: int64

## 道路タイプ

In [46]:
traffic_accident_data["road_type"] = np.where(traffic_accident_data.road_cd_f4 <= 999,
                                                                        "一般国道（国道番号）",
                                                                          traffic_accident_data.road_cd_f4)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 1000) & (traffic_accident_data.road_cd_f4 <= 1500),
                                                                        "主要地方道－都道府県道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 1500) & (traffic_accident_data.road_cd_f4 <= 1999),
                                                                        "主要地方道－市道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 2000) & (traffic_accident_data.road_cd_f4 <= 2999),
                                                                        "一般都道府県道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 3000) & (traffic_accident_data.road_cd_f4 <= 3999),
                                                                        "一般市町村道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 4000) & (traffic_accident_data.road_cd_f4 <= 4999),
                                                                        "高速自動車国道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 5000) & (traffic_accident_data.road_cd_f4 <= 5499),
                                                                        "自動車専用道－指定",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 5500) & (traffic_accident_data.road_cd_f4 <= 5999),
                                                                        "自動車専用道－その他",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 6000) & (traffic_accident_data.road_cd_f4 <= 6999),
                                                                        "道路運送法上の道路",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 7000) & (traffic_accident_data.road_cd_f4 <= 7999),
                                                                        "農（免）道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 8000) & (traffic_accident_data.road_cd_f4 <= 8499),
                                                                        "林道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 8500) & (traffic_accident_data.road_cd_f4 <= 8999),
                                                                        "港湾道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( (traffic_accident_data.road_cd_f4 >= 9000) & (traffic_accident_data.road_cd_f4 <= 9499),
                                                                        "私道",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( traffic_accident_data.road_cd_f4 == 9500,
                                                                        "その他",
                                                                          traffic_accident_data.road_type)
traffic_accident_data["road_type"] = np.where( traffic_accident_data.road_cd_f4 == 9900,
                                                                        "一般の交通の用に供するその他の道路",
                                                                          traffic_accident_data.road_type)

In [47]:
traffic_accident_data["road_type"].head()

0    高速自動車国道
1    高速自動車国道
2    高速自動車国道
3    高速自動車国道
4     一般市町村道
Name: road_type, dtype: object

In [48]:
traffic_accident_data["road_bypass"] = np.where(traffic_accident_data.road_cd_l1 > 0, "バイパス区間",
                                                                           np.where(traffic_accident_data.road_cd_l1 == 0, "現道区間又は包括路線", None))

```
if traffic_accident_data.road_cd_l1 > 0:
    バイパス区間
elif traffic_accident_data.road_cd_l1 == 0:
    現道区間又は包括路線
else:
    None
```

In [51]:
traffic_accident_data.road_type.value_counts(normalize=True)

一般市町村道               0.457733
主要地方道－都道府県道          0.171009
一般都道府県道              0.142041
一般国道（国道番号）           0.108167
一般の交通の用に供するその他の道路    0.042899
主要地方道－市道             0.032796
高速自動車国道              0.024953
自動車専用道－指定            0.009122
その他                  0.006705
港湾道                  0.001514
農（免）道                0.001180
私道                   0.001041
自動車専用道－その他           0.000634
林道                   0.000127
道路運送法上の道路            0.000078
Name: road_type, dtype: float64

In [50]:
traffic_accident_data.road_bypass.value_counts()

現道区間又は包括路線    679621
バイパス区間         10794
Name: road_bypass, dtype: int64

## 道路のタイプ(その他)

In [52]:
import re

def multiple_replace(text, adict):
    rx = re.compile('|'.join(adict))
    
    def dedictkey(text):
        for key in adict.keys():
            if re.search(key, text):
                return key
 
    def one_xlat(match):
        return adict[dedictkey(match.group(0))]
 
    return rx.sub(one_xlat, text)

```
def outer_function():
    # 外側の関数の定義

    def inner_function():
        # 内側の関数の定義

    inner_function() # これはOK

inner_function() # これはNG
```

In [53]:
traffic_accident_data['上下線'].astype(str).head()

0    1
1    1
2    1
3    1
4    0
Name: 上下線, dtype: object

In [56]:
traffic_accident_data['上下線'].astype(str).value_counts()

0    589042
1     52907
2     48466
Name: 上下線, dtype: int64

In [60]:
replace_list.keys()

dict_keys(['1', '2', '0'])

In [57]:
replace_list = {'1':'上','2':'下','0':'対象外'}

traffic_accident_data['road_updown_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['上下線'].astype(str)))

第一引数に関数、第二引数に加工元となる値群を指定

In [58]:
traffic_accident_data['road_updown_type'].head()

0      上
1      上
2      上
3      上
4    対象外
Name: road_updown_type, dtype: object

## 昼夜

In [62]:
traffic_accident_data['昼夜'].unique()

array([11, 23, 12, 22, 21, 13])

In [63]:
replace_list = {'11':'昼－明',
                      '12':' 昼－昼',
                      '13':' 昼－暮',
                      '21':'夜－暮',
                      '22':'夜－夜',
                      '23':'夜－明'
                        }

traffic_accident_data['day_night_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['昼夜'].astype(str)))

## 天候

In [64]:
replace_list = {'1':'晴',
                      '2':'曇',
                      '3':'雨',
                      '4':'霧',
                      '5':'雪'
                        }

traffic_accident_data['weather_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['天候'].astype(str)))

## 地形

In [65]:
replace_list = {'1':'市街地－人口集中',
                      '2':'市街地－その他',
                      '3':'非市街地',
                        }

traffic_accident_data['terrain_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['地形'].astype(str)))

## 路面状態

In [66]:
replace_list = {'1':'舗装－乾燥',
                      '2':'舗装－湿潤',
                      '3':'舗装－凍結',
                      '4':'舗装－積雪',
                      '5':'非舗装',
                        }

traffic_accident_data['road_condition_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['路面状態'].astype(str)))

## 道路形状

In [67]:
replace_list = {'31':'交差点－環状交差点',
                      '^1$':'交差点－その他',
                      '37':'交差点付近－環状交差点付近',
                      '^7$':'交差点付近－その他',
                      '11':'単路－トンネル',
                      '12':'単路－橋',
                      '13':'単路－カーブ・屈折',
                      '14':'単路－その他',
                      '21':'踏切－第一種',
                      '22':'踏切－第三種',
                      '23':'踏切－第四種',
                      '^0$':'一般交通の場所'
                        }

traffic_accident_data['road_shape_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['道路形状'].astype(str)))

## 環状交差点の直径

In [68]:
replace_list = {'^1$':'小（27ｍ未満）',
                      '^2$':'中（27ｍ以上）',
                      '^3$':'大（43ｍ以上）',
                      '^0$':'環状交差点以外',
                        }

traffic_accident_data['roundabout_diameter_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['環状交差点の直径'].astype(str)))

## 信号機

In [69]:

replace_list = {'^1$':'点灯－３灯式',
                      '^8$':'点灯－歩車分式',
                      '^2$':'点灯－押ボタン式',
                      '^3$':'点滅－３灯式',
                      '^4$':'点滅－１灯式',
                      '^5$':'消灯',
                      '^6$':'故障',
                      '^7$':'施設なし'
                        }

traffic_accident_data['traffic_lights_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['信号機'].astype(str)))

## 一時停止規制　標識

In [70]:
replace_list = {'^1$':'標準－反射式',
                      '^2$':'標準－自発光式',
                      '^3$':'標準－内部照明式',
                      '^4$':'拡大－反射式',
                      '^5$':'拡大－自発光式',
                      '^6$':'拡大－内部照明式',
                      '^7$':'縮小',
                      '^8$':'その他',
                      '^9$':'規制なし',
                      '^0$':'対象外当事者',
                        }

traffic_accident_data['pause_sign_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['一時停止規制\u3000標識（当事者A）'].astype(str)))
traffic_accident_data['pause_sign_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['一時停止規制\u3000標識（当事者B）'].astype(str)))

## 一時停止規制　表示

In [71]:

replace_list = {'^21$':'表示あり',
                      '^22$':'表示なし',
                      '^23$':'その他',
                        }

traffic_accident_data['pause_display_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['一時停止規制\u3000表示（当事者A）'].astype(str)))
traffic_accident_data['pause_display_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['一時停止規制\u3000表示（当事者B）'].astype(str)))

## 車道幅員

In [72]:

replace_list = {'^1$':'単路－3.5m未満',
                      '^2$':'単路－3.5m以上',
                      '^3$':'単路－5.5m以上',
                      '^4$':'単路－9.0m以上',
                      '^5$':'単路－13.0m以上',
                      '^6$':'単路－19.5m以上',
                      '^11$':'交差点－小（5.5m未満）－小',
                      '^14$':'交差点－中（5.5m以上）－小',
                      '^15$':'交差点－中（5.5m以上）－中',
                      '^17$':'交差点－大（13.0ｍ以上）－小',
                      '^18$':'交差点－大（13.0ｍ以上）－中',
                      '^19$':'交差点－大（13.0ｍ以上）－大',                
                      '^0$':'一般交通の場所',
                        }

traffic_accident_data['road_width_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['車道幅員'].astype(str)))

## 道路線形

In [73]:

replace_list = {'^1$':'カーブ・屈折－右－上り',
                      '^2$':'カーブ・屈折－右－下り',
                      '^3$':'カーブ・屈折－右－平坦',
                      '^4$':'カーブ・屈折－左－上り',
                      '^5$':'カーブ・屈折－左－下り',
                      '^6$':'カーブ・屈折－左－平坦',
                      '^7$':'直線－上り',
                      '^8$':'直線－下り',
                      '^9$':'直線－平坦',
                      '^0$':'一般交通の場所',
                        }

traffic_accident_data['road_alignment_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['道路線形'].astype(str)))

## 衝突地点

In [74]:

replace_list = {'^1$':'単路（交差点付近を含む）',
                      '^30$':'交差点内',
                      '^20$':'その他',
                        }

traffic_accident_data['road_alignment_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['衝突地点'].astype(str)))

## ゾーン規制

In [75]:

replace_list = {'^1$':'ゾーン30',
                      '^70$':'規制なし',
                        }

traffic_accident_data['zone_regulation_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['ゾーン規制'].astype(str)))

## 中央分離帯施設等

In [76]:

replace_list = {'^1$':'中央分離帯',
                      '^2$':'中央線－高輝度標示',
                      '^3$':'中央線－チャッターバー等',
                      '^6$':'中央線－ポストコーン', 
                      '^4$':'中央線－ペイント',
                      '^5$':'中央分離なし',
                      '^0$':'一般交通の場所',                
                        }

traffic_accident_data['zone_regulation_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                traffic_accident_data['中央分離帯施設等'].astype(str)))

## 歩車道区分

In [77]:

replace_list = {'^1$':'区分あり－防護柵等',
                      '^2$':'区分あり－縁石・ブロック等',
                      '^3$':'区分あり－路側帯',
                      '^4$':'区分なし', 
                        }

traffic_accident_data['pedestrian_road_division_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['歩車道区分'].astype(str)))

## 事故類型

In [78]:

replace_list = {'^1$':'人対車両',
                      '^21$':'車両相互',
                      '^41$':'車両単独',
                      '^61$':'列車', 
                        }

traffic_accident_data['accident_vehicle_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['事故類型'].astype(str)))

## 年齢

In [79]:

replace_list = {'^1$':'0～24歳',
                      '^25$':'25～34歳',
                      '^35$':'35～44歳',
                      '^45$':'45～54歳', 
                      '^55$':'55～64歳',
                      '^65$':'65～74歳', 
                      '^75$':'75歳以上',
                      '^0$':'不明',                
                        }

traffic_accident_data['age_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['年齢（当事者A）'].astype(str)))
traffic_accident_data['age_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['年齢（当事者B）'].astype(str)))

## 当事者種別

In [80]:

replace_list = {'^1$':'乗用車－大型車',
                      '^2$':'乗用車－中型車',
                      '^7$':'乗用車－準中型車',
                      '^3$':'乗用車－普通車',
                      '^4$':'乗用車－軽自動車',
                      '^5$':'乗用車－ミニカー',
                      '^11$':'貨物車－大型車',
                      '^12$':'貨物車－中型車',
                      '^17$':'貨物車－準中型車',
                      '^13$':'貨物車－普通車',
                      '^14$':'貨物車－軽自動車',
                      '^21$':'特殊車－大型－農耕作業用',
                      '^22$':'特殊車－大型－その他',
                      '^23$':'特殊車－小型－農耕作業用',
                      '^24$':'特殊車－小型－その他',
                      '^31$':'二輪車－自動二輪－小型二輪－751ｃｃ以上', 
                      '^32$':'二輪車－自動二輪－小型二輪－401～750ｃｃ',
                      '^33$':'二輪車－自動二輪－小型二輪－251～400cc',
                      '^34$':'二輪車－自動二輪－軽二輪－126～250cc',
                      '^35$':'二輪車－自動二輪－原付二種－51～125cc', 
                      '^36$':'二輪車－原付自転車',
                      '^41$':'路面電車',
                      '^42$':'列車',
                      '^51$':'軽車両－自転車',
                      '^52$':'軽車両－駆動補助機付自転車',
                      '^59$':'軽車両－その他',
                      '^61$':'歩行者',
                      '^71$':'歩行者以外の道路上の人（補充票のみ）',
                      '^72$':'道路外の人（補充票のみ）',
                      '^75$':'物件等',
                      '^76$':'相手なし',
                      '^0$':'対象外当事者',                
                        }

traffic_accident_data['parties_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['当事者種別（当事者A）'].astype(str)))
traffic_accident_data['parties_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['当事者種別（当事者B）'].astype(str)))

## 用途別

In [81]:

replace_list = {'^1$':'事業用',
                      '^31$':'自家用',
                      '^0$':'対象外当事者',
                      '^$':'ー', 
                        }

traffic_accident_data['use_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['用途別（当事者A）'].astype(str)))
traffic_accident_data['use_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['用途別（当事者B）'].astype(str)))

## 車両形状

In [82]:

replace_list = {'^1$':'乗用車',
                      '^11$':'貨物車',
                      '^0$':'対象外当事者',
                      '^$':'ー', 
                        }

traffic_accident_data['vehicle_shape_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['車両形状（当事者A）'].astype(str)))
traffic_accident_data['vehicle_shape_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['車両形状（当事者B）'].astype(str)))

## 速度規制（指定のみ）

In [83]:

replace_list = {'^1$':'20㎞／ｈ以下',
                      '^2$':'30㎞／ｈ以下',
                      '^3$':'40㎞／ｈ以下',
                      '^4$':'50㎞／ｈ以下',
                      '^5$':'60㎞／ｈ以下',
                      '^6$':'70㎞／ｈ以下',
                      '^7$':'80㎞／ｈ以下',
                      '^8$':'100㎞/h以下',
                      '^9$':'100㎞/h超過',
                      '^10$':'指定の速度規制なし等',
                      '^0$':'対象外当事者',                
                        }

traffic_accident_data['speed_regulation_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['速度規制（指定のみ）（当事者A）'].astype(str)))
traffic_accident_data['speed_regulation_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['速度規制（指定のみ）（当事者B）'].astype(str)))

## 車両の衝突部位

In [84]:

replace_list = {'^1':'前_中央_',
                      '^2':'右_中央_',
                      '^3':'後_中央_',
                      '^4':'左_中央_',
                      '^5':'前_右_',
                      '^6':'後_右_',
                      '^7':'後_左_',
                      '^8':'前_左_',
                      '^0':'それ以外_',                
                        }

traffic_accident_data['collision_site_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['車両の衝突部位（当事者A）'].astype(str)))
traffic_accident_data['collision_site_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['車両の衝突部位（当事者B）'].astype(str)))
replace_list = {'1$':'前_中央',
                      '2$':'右_中央',
                      '3$':'後_中央',
                      '4$':'左_中央',
                      '5$':'前_右',
                      '6$':'後_右',
                      '7$':'後_左',
                      '8$':'前_左',
                      '0$':'それ以外',                
                        }

traffic_accident_data['collision_site_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['collision_site_type_a'].astype(str)))
traffic_accident_data['collision_site_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['collision_site_type_b'].astype(str)))

## 車両の損壊程度

In [85]:

replace_list = {'^1$':'大破',
                      '^2$':'中破',
                      '^3$':'小破',
                      '^4$':'損壊なし',
                      '^0$':'対象外当事者',
                      '^$':'ー',   
                        }

traffic_accident_data['damage_to_vehicle_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['車両の損壊程度（当事者A）'].astype(str)))
traffic_accident_data['damage_to_vehicle_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['車両の損壊程度（当事者B）'].astype(str)))

## エアバッグの装備

In [86]:

replace_list = {'^1$':'装備あり作動',
                      '^2$':'その他',
                      '^0$':'対象外当事者',
                        }

traffic_accident_data['airbag_equipment_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['エアバッグの装備（当事者A）'].astype(str)))
traffic_accident_data['airbag_equipment_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['エアバッグの装備（当事者B）'].astype(str)))

## サイドエアバッグの装備

In [87]:

replace_list = {'^1$':'装備あり作動',
                      '^2$':'その他',
                      '^0$':'対象外当事者',
                        }

traffic_accident_data['side_airbag_equipment_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['サイドエアバッグの装備（当事者A）'].astype(str)))
traffic_accident_data['side_airbag_equipment_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['サイドエアバッグの装備（当事者B）'].astype(str)))

## 人身損傷程度

In [88]:

replace_list = {'^1$':'死亡',
                      '^2$':'負傷',
                      '^4$':'損傷なし',                
                      '^0$':'対象外当事者',
                        }

traffic_accident_data['personal_injury_type_a'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['人身損傷程度（当事者A）'].astype(str)))
traffic_accident_data['personal_injury_type_b'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['人身損傷程度（当事者B）'].astype(str)))

## 曜日(発生年月日)

In [90]:
traffic_accident_data['曜日(発生年月日)'].head()

0    2
1    5
2    1
3    6
4    1
Name: 曜日(発生年月日), dtype: int64

In [91]:

replace_list = {'^1$':'日',
                      '^2$':'月',
                      '^3$':'火',
                      '^4$':'水', 
                      '^5$':'木', 
                      '^6$':'金',                 
                      '^7$':'土',                 
                        }

traffic_accident_data['weekday_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['曜日(発生年月日)'].astype(str)))

## 祝日

In [92]:

replace_list = {'^1$':'当日',
                      '^2$':'前日',
                      '^3$':'その他',
                        }

traffic_accident_data['holiday_type'] = list(map(lambda text:multiple_replace(text, replace_list) ,
                                                                                            traffic_accident_data['祝日(発生年月日)'].astype(str)))

In [93]:

traffic_accident_data["death_flag"] = np.where(traffic_accident_data["accident_type"] == "死亡", 1, 0)

In [95]:
# traffic_accident_data.to_pickle("data/traffic_accident_data.pickle")